---
driver:
  name: docker

driver_config:
  hostname: salt-formula.ci.local
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  cap_add:
    - SYS_PTRACE

platforms:
  - name: debian-9
  - name: centos-7

provisioner:
  name: salt_solo
  require_chef: false
  salt_version: latest
  formula: systemd
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    systemd.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - systemd
  state_top:
    base:
      '*':
        - systemd
        - systemd.networkd
        - systemd.networkd.profiles

suites:
  - name: deb
    excludes:
      - centos-7

  - name: rpm
    excludes:
      - debian-9
