---
driver:
  name: docker

driver_config:
  hostname: salt-formula.ci.local
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        - yum -y install initscripts 
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      pid_one_command: /usr/lib/systemd/systemd
  - name: debian-9
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd
      pid_one_command: /lib/systemd/systemd

provisioner:
  name: salt_solo
  require_chef: false
  salt_version: latest
  formula: systemd
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    systemd.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - systemd

verifier:
  name: serverspec

suites:
  - name: centos
    verifier:
      default_pattern: true
    includes:
      - centos-7
    provisioner:
      state_top:
        base:
          '*':
            - systemd
            - systemd.networkd
            - systemd.networkd.profiles
  - name: ntp
    verifier:
      default_pattern: true
    includes:
      - debian-9
    provisioner:
      state_top:
        base:
          '*':
            - systemd
            - systemd.networkd
            - systemd.networkd.profiles
            - systemd.timesyncd
