---
driver:
  name: docker

driver_config:
  hostname: salt-formula.ci.local
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: debian-stretch
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd --system
      pid_one_command: /lib/systemd/systemd

provisioner:
  name: salt_solo
  require_chef: false
  salt_version: latest
  formula: systemd
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    systemd.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - systemd
  state_top:
    base:
      '*':
        - systemd
        - systemd.networkd
        - systemd.networkd.profiles
        - systemd.timesyncd

verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      default_pattern: true
