---
driver:
  name: docker

driver_config:
  hostname: salt-formula.ci.local
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  cap_add:
    - SYS_PTRACE

platforms:
  - name: centos-7
    driver_config:
      provision_command:
        - yum -y install initscripts 
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd
      pid_one_command: /lib/systemd/systemd
      privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  salt_version: latest
  formula: systemd
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    systemd.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - systemd
  state_top:
    base:
      '*':
        - systemd
        - systemd.networkd
        - systemd.networkd.profiles

suites:
  - name: default
