sudo: required
cache: bundler
language: ruby

services:
  - docker

install:
  - bundle install

env:
  matrix:
    - INSTANCE: centos-7
    - INSTANCE: debian-9
    - INSTANCE: ubuntu-1804

script: 
  - bundle exec kitchen verify ${INSTANCE}

before_deploy:
  # Only deploy if the build passed successfully
  - test $TRAVIS_TEST_RESULT = 0
